/*
 *
 * jQuery floatingmessage.js
 *
*/

(function(e){var t={"top-left":10,"top-right":10,"bottom-left":10,"bottom-right":10},n=10,r={"top-left":[],"top-right":[],"bottom-left":[],"bottom-right":[]},i=function(t){var n,i=t.attr("id"),s=t.data("floating-message"),o={},u=0,a=s.range,f=s.position,l=s.duration,c=s.stuffEasing,h=s.hide,p=s.close,d=s.timerId,v=s.height+s.margin+s.padding*2,m=r[s.position];d&&clearTimeout(d);for(n=0;n<m.length;n++){s=m[n];if(i==s.id){u=n;continue}s.range>a&&(s.range-=v,o[s.verticalAlign]=s.range,s.elem.stop().animate(o,{duration:l,easing:c,queue:!1}))}m.splice(u,1),t.stop().hide(h,l,function(){e(this).remove(),p&&p()})};e.floatingMessage=function(s,o){var u="jqueryFloatingMessage"+(new Date).getTime()+""+parseInt(Math.random()*1e4,10),a=e('<div id="'+u+'" class="ui-corner-all ui-floating-message"></div>'),f={},l=0,c=0,h;return o=o||{},o=e.extend(!0,{position:"top-left",verticalAlign:(o.position||"top-left").split("-")[0],align:(o.position||"top-left").split("-")[1],width:300,height:50,time:!1,show:"drop",hide:"drop",padding:10,margin:10,duration:500,stuffEasing:"easeOutBounce",body:e("<div></div>"),open:!1,close:!1,click:i,elem:a,timerId:!1,id:u},o),o.range=t[o.position],l=o.height,c=o.padding,h=o.open,s&&o.body.html(s.replace(/\n/g,"<br />")),o.className&&a.addClass(o.className),f={width:o.width+"px",height:l+"px",zIndex:"9999",position:"fixed",padding:c+"px"},f[o.verticalAlign]=(e(window).height()-o.height)/2-t[o.position],f[o.align]=(e(window).width()-o.width)/2-n,a.css(f).append(o.body),a.bind("destroy.fms",function(){i(a)}),e(document.body).append(a),o.click&&a.bind("click.fms",function(){o.click(a)}),a.show(o.show,o.duration,function(){o.time&&(o.timerId=setTimeout(function(){o.click(a)},o.time)),h&&h()}),r[o.position].push(o),a.data("floating-message",o),o.body},e.fn.floatingMessage=function(t){return this.each(function(){typeof t=="string"?e(this).parent(".ui-floating-message").trigger(t+".fms"):(t=t||{},t.body=this,e.floatingMessage(!1,t))})}})(jQuery);

/*
 * hyip.min.js for Ajax (2013-12-11)
 * 
 * Depends jquery.floatinmessage.js
 * 
 */

var HYIP={};HYIP={};HYIP.ajaxTryTimes=0;HYIP.ajax=function(c,f,e,a,d,b,g){g=g||1;f.r=Math.random()*10;$.ajax({url:c,dataType:"json",timeout:30000,data:f,type:"post",cache:false,success:function(h){if(h.success){(e||function(){})(h)}else{if(a){a(h)}else{if(h.message){HYIP.showDynamicErrorMsg(h.message)}}}(d||function(){})(h)},error:function(h,k,j){if(g>=HYIP.ajaxTryTimes){if(b){b()}else{HYIP.showDynamicErrorMsg()}}else{g++;HYIP.ajax(c,f,e,a,d,b,g)}}})};HYIP.dynamicTimers=[];HYIP.dynamicOption={};HYIP.showDynamicMsg=function(d,a,c,b){if($("#"+d).size()==0){$("body").append('<span id="'+d+'"></span>');HYIP.dynamicOption[d]={of:$(window)}}$("#"+d).hide();for(i in HYIP.dynamicTimers){clearTimeout(HYIP.dynamicTimers[i])}HYIP.dynamicTimers=[];$("#"+d).removeAttr("class").addClass(a).css("z-index",9999).html(c).fadeIn("blind",function(){$("#"+d).position(HYIP.dynamicOption[d]);var e=setTimeout(function(){$("#"+d).fadeOut("blind")},b||3000);HYIP.dynamicTimers.push(e)})};HYIP.showDynamicSuccessMsg=function(d,c){d=d||"";var e=!!window.ActiveXObject&&!window.XMLHttpRequest;if(e){HYIP.showDynamicMsg("hyip_float_message","hyip-success",d,c)}else{var b=(d.length>10)?500:150;var a=(d.length>70)?52:20;$.floatingMessage(d,{show:"blind",hide:"puff",width:b,height:a,time:c||3000,position:"top-left",className:"hyip-success"})}};HYIP.showDynamicErrorMsg=function(c,b){c=c||"";if(c==""||c=="网络错误"){return}var d=!!window.ActiveXObject&&!window.XMLHttpRequest;if(d){HYIP.showDynamicMsg("hyip_float_message","hyip-failed",c,b)}else{var a=(c.length>10)?500:150;$.floatingMessage(c,{show:"blind",hide:"puff",width:a,height:20,time:b||3000,position:"top-left",className:"hyip-failed"})}};HYIP.isInt=function(a){return/^\d+$/.test(a)};HYIP.parseInt=function(a){return HYIP.isInt(a)?parseInt(a):0};HYIP.formatMoney=function fmoney(b,d){d=d>0&&d<=20?d:2;b=parseFloat((b+"").replace(/[^\d\.-]/g,"")).toFixed(d)+"";var a=b.split(".")[0].split("").reverse(),c=b.split(".")[1];t="";for(i=0;i<a.length;i++){t+=a[i]+((i+1)%3==0&&(i+1)!=a.length?",":"")}return t.split("").reverse().join("")+"."+c};
